import { Injectable, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, tap } from 'rxjs';
import { environment } from '../../environments/environment';
import {
  CreateStockCountRequest,
  StockCountDto,
  StockCountPrintDto,
  StockCountSearchRequest,
} from '../models/stock-count.model';

@Injectable({
  providedIn: 'root'
})
export class StockCountService {
  private apiUrl = `${environment.apiUrl}/stock-counts`;

  stockCounts = signal<StockCountDto[]>([]);
  totalCount = signal<number>(0);
  isLoading = signal<boolean>(false);
  error = signal<string | null>(null);

  constructor(private http: HttpClient) {}

  search(request: StockCountSearchRequest): Observable<any> {
    this.isLoading.set(true);
    this.error.set(null);

    return this.http.post<any>(`${this.apiUrl}/search`, request).pipe(
      tap({
        next: (response) => {
          const data = response.data;
          this.stockCounts.set(data?.stockCounts || []);
          this.totalCount.set(data?.totalCount || 0);
          this.isLoading.set(false);
        },
        error: (err) => {
          this.error.set(err.message || 'Failed to load stock counts');
          this.isLoading.set(false);
        }
      })
    );
  }

  getById(id: number): Observable<any> {
    return this.http.get<any>(`${this.apiUrl}/${id}`);
  }

  create(request: CreateStockCountRequest): Observable<any> {
    this.isLoading.set(true);
    this.error.set(null);

    return this.http.post<any>(this.apiUrl, request).pipe(
      tap({
        next: () => this.isLoading.set(false),
        error: (err) => {
          this.error.set(err.message || 'Failed to create stock count');
          this.isLoading.set(false);
        }
      })
    );
  }

  downloadExcel(id: number): Observable<Blob> {
    return this.http.get(`${this.apiUrl}/${id}/download`, { responseType: 'blob' });
  }

  getPrintData(id: number): Observable<any> {
    return this.http.get<any>(`${this.apiUrl}/${id}/print`);
  }

  submit(id: number): Observable<any> {
    return this.http.post<any>(`${this.apiUrl}/${id}/submit`, {});
  }

  approve(id: number): Observable<any> {
    return this.http.post<any>(`${this.apiUrl}/${id}/approve`, {});
  }

  reject(id: number, reason?: string): Observable<any> {
    return this.http.post<any>(`${this.apiUrl}/${id}/reject`, {
      reason: reason || null,
    });
  }

  reopen(id: number): Observable<any> {
    return this.http.post<any>(`${this.apiUrl}/${id}/reopen`, {});
  }

  upload(id: number, file: File): Observable<any> {
    const formData = new FormData();
    formData.append('file', file);
    return this.http.post<any>(`${this.apiUrl}/${id}/upload`, formData);
  }

  generateAdjustmentDraft(id: number): Observable<any> {
    return this.http.post<any>(`${this.apiUrl}/${id}/generate-adjustment-draft`, {});
  }

  printDocument(printData: StockCountPrintDto): void {
    const popup = window.open('', '_blank', 'width=1200,height=900');
    if (!popup) {
      return;
    }

    const rows = printData.lines
      .map((line, index) => `
        <tr>
          <td>${index + 1}</td>
          <td>${line.productName}</td>
          <td>${line.productCode}</td>
          <td>${line.variantName}</td>
          <td style="text-align:right;">${line.currentStock ?? ''}</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>`)
      .join('');

    popup.document.write(`
      <html>
        <head>
          <title>Stock Count ${printData.stockCountNo}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { margin: 0; font-size: 20px; }
            .meta { margin: 12px 0; font-size: 13px; color: #333; }
            table { width: 100%; border-collapse: collapse; margin-top: 14px; }
            th, td { border: 1px solid #ddd; padding: 8px; font-size: 12px; }
            th { background: #f4f4f4; text-align: left; }
            .warn { margin-top: 10px; padding: 8px; background: #fff7ed; border: 1px solid #fdba74; color: #9a3412; font-size: 12px; }
            @media print { @page { size: A4 landscape; margin: 12mm; } }
          </style>
        </head>
        <body>
          <h1>${printData.companyName}</h1>
          <div class="meta">
            <div><strong>Stock Count No:</strong> ${printData.stockCountNo}</div>
            <div><strong>Location:</strong> ${printData.locationName} (${printData.locationType})</div>
            <div><strong>Stock Count Date:</strong> ${new Date(printData.stockCountDate).toLocaleDateString()}</div>
            <div><strong>Generated By:</strong> ${printData.generatedBy}</div>
            <div><strong>Generated At:</strong> ${new Date(printData.generatedAt).toLocaleString()}</div>
          </div>
          ${printData.hasPostGenerationMovements ? `<div class="warn"><strong>Warning:</strong> ${printData.postGenerationMovementCount} inventory movements occurred after generation.</div>` : ''}
          <table>
            <thead>
              <tr>
                <th>SL</th>
                <th>Product Name</th>
                <th>Product Code</th>
                <th>Variant</th>
                <th>Current Stock</th>
                <th>Physical Count</th>
                <th>Difference</th>
                <th>Remarks</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>
        </body>
      </html>
    `);

    popup.document.close();
    popup.focus();
    popup.print();
  }
}
