import { Component, OnInit, signal } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { RouterLink } from '@angular/router';
import { GrnService } from '../../services/grn.service';
import { AlertService } from '../../services/alert.service';
import { ErrorHandlerService } from '../../services/error-handler.service';
import { DocumentPdfService } from '../../services/document-pdf.service';
import { SettingsService } from '../../services/settings.service';
import { Grn } from '../../models/grn.model';

@Component({
  selector: 'app-grn-details',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './grn-details.component.html',
  styleUrls: ['./grn-details.component.css']
})
export class GrnDetailsComponent implements OnInit {
  grn = signal<Grn | null>(null);
  isLoading = signal(false);
  isCompleting = signal(false);
  isPdfDownloading = signal(false);
  businessTimeZone = signal<string>('Asia/Dhaka');

  constructor(
    private grnService: GrnService,
    private router: Router,
    private location: Location,
    private route: ActivatedRoute,
    private alertService: AlertService,
    private errorHandler: ErrorHandlerService,
    private documentPdfService: DocumentPdfService,
    private settingsService: SettingsService
  ) {}

  ngOnInit(): void {
    this.loadBusinessTimeZone();
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadGrn(+id);
    }
  }

  private loadBusinessTimeZone(): void {
    this.settingsService.getCompanySettings().subscribe({
      next: (res) => {
        const tz = res?.data?.timeZone;
        if (typeof tz === 'string' && tz.trim()) {
          this.businessTimeZone.set(tz.trim());
        }
      },
      error: () => {
        // Fall back to default timezone if settings cannot be loaded.
      }
    });
  }

  loadGrn(id: number): void {
    this.isLoading.set(true);
    this.grnService.getById(id).subscribe({
      next: (response) => {
        this.grn.set(response.data || null);
        this.isLoading.set(false);
      },
      error: (err) => {
        this.alertService.error(this.errorHandler.extractErrorMessage(err));
        this.isLoading.set(false);
        this.location.back();
      }
    });
  }

  completeGrn(): void {
    const grn = this.grn();
    if (!grn) return;
    this.alertService.confirm('Complete this GRN and update stock levels?', () => {
      this.isCompleting.set(true);
      this.grnService.complete(grn.id).subscribe({
        next: () => {
          this.alertService.success('GRN completed and stock updated successfully');
          this.loadGrn(grn.id);
          this.isCompleting.set(false);
        },
        error: (err) => {
          this.alertService.error(this.errorHandler.extractErrorMessage(err));
          this.isCompleting.set(false);
        }
      });
    });
  }

  getPoReference(grn: Grn): string {
    return grn.poOrderNumber || grn.poNumber || `PO-${grn.poId.toString().padStart(6, '0')}`;
  }

  getVariantDetails(item: { variantName?: string; variantAttributes?: string }): string {
    const parts = [item.variantName, item.variantAttributes]
      .map(v => (v ?? '').trim())
      .filter(v => this.hasReadableText(v))
      .filter(v => v.length > 0);

    return parts.join(' - ');
  }

  private hasReadableText(value: string): boolean {
    const trimmed = value.trim();
    if (!trimmed) return false;
    if (trimmed === '{}' || trimmed === '[]' || trimmed.toLowerCase() === 'null') return false;
    if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) return false;
    return true;
  }

  getCreatedByLabel(grn: Grn): string {
    const createdByName = (grn.creatorName ?? '').trim();
    const notes = (grn as any).notes as string | undefined;
    const isAutoGenerated = typeof notes === 'string' && notes.includes('AUTO_GENERATED_FROM_PURCHASE_ORDER');

    if (isAutoGenerated && createdByName) {
      return `System (Triggered by ${createdByName})`;
    }

    if (createdByName) {
      return createdByName;
    }

    return isAutoGenerated ? 'System' : '-';
  }

  backToList(): void {
    this.location.back();
  }

  getStatusBadgeClass(status: string): string {
    switch (status?.toLowerCase()) {
      case 'full': return 'bg-green-100 text-green-800';
      case 'partial': return 'bg-yellow-100 text-yellow-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  }

  getVarianceClass(variance: number): string {
    if (variance === 0) return 'text-gray-600';
    return variance > 0 ? 'text-green-600 font-semibold' : 'text-red-600 font-semibold';
  }

  downloadPdf(): void {
    const current = this.grn();
    if (!current) {
      return;
    }

    this.isPdfDownloading.set(true);
    this.documentPdfService.downloadDocument('grn', current.id).subscribe({
      next: (response) => {
        this.documentPdfService.triggerBrowserDownload(response, `GRN-${current.id.toString().padStart(6, '0')}.pdf`);
        this.isPdfDownloading.set(false);
      },
      error: (err) => {
        this.isPdfDownloading.set(false);
        this.alertService.error(this.errorHandler.extractErrorMessage(err));
      }
    });
  }

  formatDateTime(date: string): string {
    if (!date) return '-';

    const value = new Date(date);
    if (Number.isNaN(value.getTime())) return '-';

    const parts = new Intl.DateTimeFormat('en-GB', {
      timeZone: this.businessTimeZone(),
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    }).formatToParts(value);

    const day = parts.find(p => p.type === 'day')?.value ?? '--';
    const month = parts.find(p => p.type === 'month')?.value ?? '---';
    const year = parts.find(p => p.type === 'year')?.value ?? '----';
    const hour = parts.find(p => p.type === 'hour')?.value ?? '--';
    const minute = parts.find(p => p.type === 'minute')?.value ?? '--';
    const dayPeriod = (parts.find(p => p.type === 'dayPeriod')?.value ?? '').toUpperCase();

    return `${day} ${month}, ${year} ${hour}:${minute} ${dayPeriod}`.trim();
  }
}
