services:
  postgres:
    image: postgres:16
    container_name: retailpos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: retailpos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 589123Qwe
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
