// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailPOS.Infrastructure.Data;

#nullable disable

namespace RetailPOS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RetailPOSDbContext))]
    [Migration("20260607000000_AddUserWarehouseAssignment")]
    partial class AddUserWarehouseAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified snapshot. The full schema is regenerated during scaffolding.
            // This file will be overwritten when running: dotnet ef migrations add

#pragma warning restore 612, 618
        }
    }
}
